#!/usr/bin/env bash
# info on dmdomains and subdomains

all_sub(){
    dig "$1" | grep -A1 'ANSWER SECTION:'  | sed -r "s/$1./$2/g" | awk -F" " 'NR==2 {print "The subdomain "$1" is a "$4" record and points to "$5}'
}
if [ "$#" -eq 2 ]; then
    all_sub "$2.$1" "$2"
else
    all_sub "www.$1" "www"
    all_sub "lb-01.$1" "lb-01"
    all_sub "web-01.$1" "web-01"
    all_sub "web-02.$1" "web-02"
fi
