#!/usr/bin/env bash
# automates installation and configuration of nginx

apt update
apt install -y nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html

server_config='
server {
	listen 80;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.nginx-debian.html;


	location / {
		try_files \$uri \$uri/ =404;
	}
}'

echo "$server_config" > /etc/nginx/sites-available/default


service nginx restart
