#!/usr/bin/env bash
# configures a new ngix with hostname set

apt-get update
apt-get install -y nginx

echo "Hello" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/c404.html

server_config="
server {
	listen 80;
	listen [::]:80 default_server;

	add_header X-Served-By $HOSTNAME;

	root /var/www/html;
	index index.nginx-debian.html;

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}

	error_page 404 /c404.html;
	location =/c404.html {
		root /usr/share/nginx/html;
		internal;
	}
}"

echo "$server_config" > /etc/nginx/sites-available/default


service nginx restart
