#!/usr/bin/env bash
# automates installation and configuration of nginx
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
kill -9 "$(cat /run/nginx.pid)"
