#!/usr/bin/env bash
# creates a file containing its pid and handle signsls within a forver loop











echo "$$" > /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	trap 'echo "I hate the kill command"' SIGTERM
	trap 'echo "Y U no love me?!" rm /var/run/myscript.pid exit' SIGINT
done
